cmake_minimum_required(VERSION 3.12)
project(ghvcore LANGUAGES CXX)
add_executable(ghvcore ghvcore.cpp)
target_compile_features(ghvcore PRIVATE cxx_std_17)
if(MSVC)
  target_compile_options(ghvcore PRIVATE /O2)
else()
  target_compile_options(ghvcore PRIVATE -O3)
endif()
set_target_properties(ghvcore PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin")
