#pragma once
// Generated by tools/generate_version_header.py from VERSION.json. Do not edit.
#define GHV_PROJECT_VERSION "0.9.0-beta.1"
#define GHV_PROJECT_STATUS "beta"
#define GHV_CURRENT_GHVC 9
#define GHV_CURRENT_GHAC 1
#define GHV_LIB_VERSION "0.2.0-beta.1"
#define GHV_LIB_DECODER_LIST "7,8,9"
#define GHV_LIB_VERSION_STRING "libghv 0.2.0-beta.1 / GHVC7,8,9"
