#!/usr/bin/env python3
"""Generate native/ghv_version.h from VERSION.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "native" / "ghv_version.h"


def main() -> None:
    data = json.loads((ROOT / "VERSION.json").read_text(encoding="utf-8"))
    decoders = ",".join(str(int(v)) for v in data["libghv_supported_ghvc_decoders"])
    text = f'''#pragma once
// Generated by tools/generate_version_header.py from VERSION.json. Do not edit.
#define GHV_PROJECT_VERSION "{data['project_version']}"
#define GHV_PROJECT_STATUS "{data['project_status']}"
#define GHV_CURRENT_GHVC {int(data['current_ghvc_encoder'])}
#define GHV_CURRENT_GHAC {int(data['current_ghac_encoder'])}
#define GHV_LIB_VERSION "{data['libghv_version']}"
#define GHV_LIB_DECODER_LIST "{decoders}"
#define GHV_LIB_VERSION_STRING "libghv {data['libghv_version']} / GHVC{decoders}"
'''
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"generated {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
